### ISSUE TITLE
Alpha / Opacity option

### ISSUE THREAD

**Issue by micsun-al** [playcanvas/sprites#3]
This could use an alpha or opacity option...is there one already?

Can we access the material to change the opacity on it some how?  I'd prefer if I can change the opacity directly from the sprite though.

Thank you!

**Comment by micsun-al** [comment]
I think I just figured it out?

```
var opacity = 0.5;
this.entity.script.sprite.tint.data = [1, 1, 1, opacity];
```

Is this about right or is there a better/different way I should be doing this?

**Comment by micsun-al** [comment]
Er...

this.entity.script.sprite.tint.data[3] = opacity;

Just feels like opacity should be broken out in to a separate property or method.  Oh well! :)

**Comment by willeastcott** [comment]
Actually, you should probably do:

```
this.entity.script.sprite.tint.a = opacity;
```

That's the proper API way to do it. :) The 'data' property is not API. But both should achieve the same thing.

**Comment by willeastcott** [comment]
This was answered and should have been closed back in 2016. Closing now...
