### ISSUE TITLE
The 'click' event does not get dispatched on mobile

### ISSUE THREAD

**Issue by micsun-al** [playcanvas/sprites#4]
The onClick event never gets dispatched on mobile devices.

```
        initialize: function () {
            this.entity.script.sprite.on('click', this.onClick, this);
        },
        onClick: function(event){
            window.open('http://www.google.com/?some-click', '_blank');
        },
```

Should we be doing something like listening for touchend?

**Comment by willeastcott** [comment]
Your code looks OK to me. Can you create a minimal reproducible on playcanvas.com that shows this problem? That will help me diagnose what is going wrong.

**Comment by willeastcott** [comment]
Request for repro was never received in 2016. In the meantime, the `SpriteComponent` has been added to the engine so this repo is now retired. Closing...
