### ISSUE TITLE
mobile / tablet click fire twice? 

### ISSUE THREAD

**Issue by nosh247** [playcanvas/sprites#8]
Hi when i do 
this.LeftBtn.script.sprite.on('click', this.onLeftClick, this);    

this will fire twice, thus making it navigate more than i want it too, for example from selection 3 got es to selection 2 when i click the left button.

**Comment by willeastcott** [comment]
Maybe needs a call to [preventDefault](https://developer.mozilla.org/en-US/docs/Web/API/Event/preventDefault) in the event handler functions?
